services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    restart: always
    environment:
      - POSTGRES_DB=bookingmaster
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bookingmaster"]
      interval: 5s
      timeout: 5s
      retries: 10

  # appwrite-embedding:
  #   image: appwrite/embedding:0.1.0
  #   environment:
  #     EMBEDDING_MODELS: "BAAI/bge-small-en-v1.5" # 384 dimension
  #   container_name: appwrite-embedding
  #   restart: unless-stopped
  #   volumes:
  #     - appwrite-models:/home/embedder/models
  #   networks:
  #     - appwrite

volumes:
  postgres_data:
  appwrite-models: null